name: test stuff

on:
  workflow_dispatch:

jobs:
  deploy-to-prd:
    runs-on: ubuntu-latest
    steps:
      - name: Post success to a Slack channel
        run: | 
          exit 1

  update-slack:
    runs-on: ubuntu-latest
    needs: [ deploy-to-prd ]
    if: ${{ always() }}
    steps:
      - name: Post success to a Slack channel
        if: ${{ always() && success() }}
        run: | 
          exit 0
      - name: Post success to a Slack channel
        if: ${{ always() && failure() || cancelled()}}
        run: | 
          exit 0


