name: test stuff

on:
  workflow_dispatch:

jobs:
  deploy-to-prd:
    runs-on: ubuntu-latest
    steps:
      - name: Post success to a Slack channel
        run: | 
          exit 1

  update-slack:
    runs-on: ubuntu-latest
    needs: [ deploy-to-prd ]
    if: ${{ always() }}
    steps:
      - name: Post success to a Slack channel
        if: needs.build.result == 'success'
        run: | 
         echo "success"
         exit 0
      - name: Post failure to a Slack channel
        if: needs.build.result == 'failure'
        run: |
          echo "failure"
          exit 1
      - name: Post failure to a Slack channel
        if: needs.build.result == 'failure'
        run: |
          echo "${{needs.build.result}}"