name: test stuff

on:
  workflow_dispatch:

jobs:
  deploy-to-prd:
    runs-on: ubuntu-latest
    steps:
      - name: Post success to a Slack channel
        run: | 
          exit 1

  update-slack:
    runs-on: ubuntu-latest
    needs: [ deploy-to-prd ]
    if: ${{ always() &&  failure() || cancelled()}}
    steps:
      - name: Post failure to a Slack channel
        run: |
          echo "failure"
          exit 1

  update-test:
    runs-on: ubuntu-latest
    needs: [ deploy-to-prd ]
    if: ${{ always() &&  success() }}
    steps:
      - name: Post success to a Slack channel
        run: | 
         echo "success"
         exit 0