name: test stuff

on:
  workflow_dispatch:

jobs:
  deploy-to-prd:
    runs-on: ubuntu-latest
    steps:
      - name: Post success to a Slack channel
        run: | 
          exit 0
   
  slack-notification:
    runs-on: ubuntu-latest
    needs: [ deploy-to-prd ]
    if: ${{ always() }}
    steps:
      - name: Post success to a Slack channel
        uses: slackapi/slack-github-action@v1.14.0
        with:
          channel-id: '#slackbot-testing'
         
          slack-message: "Deployment to PRD ${{ needs.deploy-to-prd.result }}  ${{needs.deploy-to-prd.result == 'success' && ':white_check_mark:' ||  ':rotating_light:' }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}