name: test stuff

on:
  workflow_dispatch:

jobs:
   update-slack:
    runs-on: ubuntu-latest
    needs: [ deploy-to-prd ]
    if: ${{ always() }}
    steps:
      - name: Post success to a Slack channel
        if: ${{ success() }}
        run: | 
         echo "success"
         exit 0
      - name: Post failure to a Slack channel
        if: ${{ failure() }}
        run: |
          echo "failure"
          exit 1