name: Deploy to production

on:
  release:
    types: [prereleased]
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: do nothing
        shell: bash
        run: echo "hi again"