name: Deploy to PRD

on:
  release:
    types: [ published ] 

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: do nothing
        shell: bash
        run: echo "${{ github.event.release.tag_name }}"