name: Deploy to staging

on:
  workflow_dispatch:
    inputs:
      message:
        required: true

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: do nothing
        shell: bash
        run: echo "${{ inputs.message }}"